name: Generate Snake Animation and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:     

jobs:
  build:
    name: Generate and Deploy Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: B2Qs
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  
          build_dir: dist        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
